const NODE_ENV = process.env.REACT_APP_NODE_ENV! as 'local' | 'development' | 'production';

const OPEN_RESTY_API_URL = process.env.REACT_APP_OPEN_RESTY_API_URL!;
const OPEN_RESTY_PROFILE_BUCKET = process.env.REACT_APP_OPEN_RESTY_PROFILE_BUCKET!;
const PAYGATE_API_URL = process.env.REACT_APP_PAYGATE_API_URL!;

const PROFILES_CONTRACT_ADDRESS = process.env.REACT_APP_PROFILES_CONTRACT_ADDRESS!;
const NFTS_CONTRACT_ADDRESS = process.env.REACT_APP_NFTS_CONTRACT_ADDRESS!;
const INDEX_NFTS_CONTRACT_ADDRESS = process.env.REACT_APP_INDEX_NFTS_CONTRACT_ADDRESS!;

const MEMBERSHIP_CONTRACT_ADDRESS = process.env.REACT_APP_MEMBERSHIP_CONTRACT_ADDRESS!;

const STABLE_DECIMALS = +process.env.REACT_APP_STABLE_DECIMALS!;

const CHAIN_ID = +process.env.REACT_APP_CHAIN_ID!;
const CHAT_CONTRACT_ADDRESS = process.env.REACT_APP_CHAT_CONTRACT_ADDRESS!;

const SPONSOR_CONTRACT_ADDRESS = process.env.REACT_APP_SPONSOR_CONTRACT_ADDRESS!;

const PUBLIC_PROJECT_ID = process.env.REACT_APP_PUBLIC_PROJECT_ID!;

const EXPLORER_THEPOWER_URL = process.env.REACT_APP_EXPLORER_URL!;
const WALLET_THEPOWER_URL = process.env.REACT_APP_WALLET_URL!;
const HUB_THEPOWER_URL = process.env.REACT_APP_HUB_URL!;
const FAUCET_THEPOWER_URL = process.env.REACT_APP_FAUCET!;

export default {
  NODE_ENV,

  CHAIN_ID,

  OPEN_RESTY_API_URL,
  OPEN_RESTY_PROFILE_BUCKET,

  PAYGATE_API_URL,

  PROFILES_CONTRACT_ADDRESS,

  NFTS_CONTRACT_ADDRESS,
  INDEX_NFTS_CONTRACT_ADDRESS,

  MEMBERSHIP_CONTRACT_ADDRESS,

  STABLE_DECIMALS,

  PUBLIC_PROJECT_ID,

  CHAT_CONTRACT_ADDRESS,

  SPONSOR_CONTRACT_ADDRESS,

  EXPLORER_THEPOWER_URL,
  WALLET_THEPOWER_URL,
  HUB_THEPOWER_URL,
  FAUCET_THEPOWER_URL,
};
