const NODE_ENV = import.meta.env.VITE_NODE_ENV! as
  | 'test'
  | 'development'
  | 'production';

const BASENAME = import.meta.env.VITE_BASENAME! as string;

const OPEN_RESTY_API_URL = import.meta.env.VITE_OPEN_RESTY_API_URL!;
const OPEN_RESTY_PROFILE_BUCKET = import.meta.env
  .VITE_OPEN_RESTY_PROFILE_BUCKET!;

const PROFILES_CONTRACT_ADDRESS = import.meta.env
  .VITE_PROFILES_CONTRACT_ADDRESS!;
const NFTS_CONTRACT_ADDRESS = import.meta.env.VITE_NFTS_CONTRACT_ADDRESS!;
const INDEX_NFTS_CONTRACT_ADDRESS = import.meta.env
  .VITE_INDEX_NFTS_CONTRACT_ADDRESS!;

const MEMBERSHIP_CONTRACT_ADDRESS = import.meta.env
  .VITE_MEMBERSHIP_CONTRACT_ADDRESS!;

const STABLE_DECIMALS = +import.meta.env.VITE_STABLE_DECIMALS!;

const CHAIN_ID = +import.meta.env.VITE_CHAIN_ID!;
const CHAT_CONTRACT_ADDRESS = import.meta.env.VITE_CHAT_CONTRACT_ADDRESS!;

const SPONSOR_CONTRACT_ADDRESS = import.meta.env.VITE_SPONSOR_CONTRACT_ADDRESS!;

const PUBLIC_PROJECT_ID = import.meta.env.VITE_PUBLIC_PROJECT_ID!;

const EXPLORER_THEPOWER_URL = import.meta.env.VITE_EXPLORER_URL!;
const WALLET_THEPOWER_URL = import.meta.env.VITE_WALLET_URL!;
const HUB_THEPOWER_URL = import.meta.env.VITE_HUB_URL!;
const FAUCET_THEPOWER_URL = import.meta.env.VITE_FAUCET!;

export default {
  NODE_ENV,

  BASENAME,

  CHAIN_ID,

  OPEN_RESTY_API_URL,
  OPEN_RESTY_PROFILE_BUCKET,

  PROFILES_CONTRACT_ADDRESS,

  NFTS_CONTRACT_ADDRESS,
  INDEX_NFTS_CONTRACT_ADDRESS,

  MEMBERSHIP_CONTRACT_ADDRESS,

  STABLE_DECIMALS,

  PUBLIC_PROJECT_ID,

  CHAT_CONTRACT_ADDRESS,

  SPONSOR_CONTRACT_ADDRESS,

  EXPLORER_THEPOWER_URL,
  WALLET_THEPOWER_URL,
  HUB_THEPOWER_URL,
  FAUCET_THEPOWER_URL
};
